DB_HOST="${DB_HOST:=database}"
DB_PORT="${DB_PORT:=3306}"
DB_USER="${DB_USER:=mangos}"
DB_PASS="${DB_PASS:=mangos}"
DB_NAME="${DB_NAME:=mangos}"
DB_ADMIN_USER="${DB_ADMIN_USER:=root}"
DB_ADMIN_PASS="${DB_ADMIN_PASS:=mangos}"

LOGIN_DB_NAME="${LOGIN_DB_NAME:=login}"
WORLD_DB_NAME="${WORLD_DB_NAME:=world}"
CHARACTERS_DB_NAME="${CHARACTERS_DB_NAME:=characters}"

# Install dualspec
DUALSPEC_FOLDER=/opt/modules/dualspec/sql
DUALSPEC_INSTALL_FOLDER=${DUALSPEC_FOLDER}/install
DUALSPEC_UNINSTALL_FOLDER=${DUALSPEC_FOLDER}/uninstall
DUALSPEC_WORLD_SQL=${DUALSPEC_INSTALL_FOLDER}/world/world.sql
DUALSPEC_CHARACTERS_SQL=${DUALSPEC_INSTALL_FOLDER}/characters/characters.sql

mysql -u ${DB_USER} -p ${DB_PASS} -h ${DB_HOST} -P ${DB_PORT} ${WORLD_DB_NAME} < ${DUALSPEC_WORLD_SQL} 2>&1
mysql -u ${DB_USER} -p ${DB_PASS} -h ${DB_HOST} -P ${DB_PORT} ${CHARACTERS_DB_NAME} < ${DUALSPEC_CHARACTERS_SQL} 2>&1